-- 创建数据库
CREATE DATABASE `OPEN-TCC`;
DROP TABLE IF EXISTS `TCC_TRX`;
CREATE TABLE `TCC_TRX` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`REGION` VARCHAR(256) NOT NULL DEFAULT 'DEFAULT',
`GROUP_TRX_ID` CHAR(32) NOT NULL,
`BRANCH_TRX_ID` CHAR(32) NOT NULL,
`CONTENT` BLOB DEFAULT NULL,
`STATUS` TINYINT NOT NULL ,
`TRX_TYPE` TINYINT NOT NULL ,
`RETRY_TIMES` INT DEFAULT NULL ,
`VERSION` INT DEFAULT NULL ,
`GMT_CREATE` DATETIME NOT NULL ,
`GMT_MODIFIED` DATETIME NOT NULL ,
PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;